In [1]:
import pandas as pd

In [4]:
df_order_local=pd.read_csv('order-local.csv', sep='\t')
df_order_router=pd.read_csv('order-router.csv', sep='\t')

In [7]:
pd.merge(df_order_local, df_order_router, on='id', how='inner', suffixes=('_local', '_router'))

,id,dt_send_local,dt_recv_local,latency_local,dt_send_router,dt_recv_router,latency_router
0,1296530,2023-09-27 05:15:36.706294,2023-09-27 05:15:37.093248,386.954,2023-09-27 05:15:36.736,2023-09-27 05:15:36.811,75.0
1,1548607,2023-09-27 05:15:38.708028,2023-09-27 05:15:38.840203,132.175,2023-09-27 05:15:38.737,2023-09-27 05:15:38.816,79.0
2,1941202,2023-09-27 05:15:40.709867,2023-09-27 05:15:40.852565,142.698,2023-09-27 05:15:40.739,2023-09-27 05:15:40.810,71.0
3,1537887,2023-09-27 05:15:42.711830,2023-09-27 05:15:42.828269,116.439,2023-09-27 05:15:42.741,2023-09-27 05:15:42.806,65.0
4,1895990,2023-09-27 05:15:44.713470,2023-09-27 05:15:44.828015,114.545,2023-09-27 05:15:44.742,2023-09-27 05:15:44.803,61.0
5,1670588,2023-09-27 05:15:46.715474,2023-09-27 05:15:46.870116,154.642,2023-09-27 05:15:46.744,2023-09-27 05:15:46.847,103.0
6,1051275,2023-09-27 05:15:48.716717,2023-09-27 05:15:48.868970,152.253,2023-09-27 05:15:48.746,2023-09-27 05:15:48.845,99.0
7,1817476,2023-09-27 05:15:50.718626,2023-09-27 05:15:50.868816,150.190,2023-09-27 05:15:50.748,2023-09-27 05:15:50.846,98.0
8,1309301,2023-09-27 05:15:52.720198,2023-09-27 05:15:52.872846,152.648,2023-09-27 05:15:52.749,2023-09-27 05:15:52.849,100.0
9,1025017,2023-09-27 05:15:54.721623,2023-09-27 05:15:54.869695,148.072,2023-09-27 05:15:54.751,2023-09-27 05:15:54.847,96.0

In [8]:
df_cancel_local=pd.read_csv('cancel-local.csv', sep='\t')
df_cancel_router=pd.read_csv('cancel-router.csv', sep='\t')

In [9]:
pd.merge(df_cancel_local, df_cancel_router, on='id', how='inner', suffixes=('_local', '_router'))

,id,dt_send_local,dt_recv_local,latency_local,dt_send_router,dt_recv_router,latency_router
0,1996795,2023-09-27 05:16:00.228269,2023-09-27 05:16:01.334553,1106.284,2023-09-27 05:16:00.257,2023-09-27 05:16:01.300,1043.0
1,1749418,2023-09-27 05:16:00.229946,2023-09-27 05:16:03.272419,3042.473,2023-09-27 05:16:00.268,2023-09-27 05:16:03.247,2979.0
2,1636535,2023-09-27 05:16:00.232126,2023-09-27 05:16:01.715321,1483.195,2023-09-27 05:16:00.268,2023-09-27 05:16:01.692,1424.0
3,1068023,2023-09-27 05:16:00.233175,2023-09-27 05:16:02.409277,2176.102,2023-09-27 05:16:00.268,2023-09-27 05:16:02.310,2042.0
4,1267369,2023-09-27 05:16:00.234149,2023-09-27 05:16:00.790962,556.813,2023-09-27 05:16:00.269,2023-09-27 05:16:00.764,495.0
5,1441543,2023-09-27 05:16:00.235031,2023-09-27 05:16:02.834011,2598.980,2023-09-27 05:16:00.269,2023-09-27 05:16:02.803,2534.0
6,1829753,2023-09-27 05:16:00.236063,2023-09-27 05:16:01.280371,1044.308,2023-09-27 05:16:00.270,2023-09-27 05:16:01.258,988.0
7,1222779,2023-09-27 05:16:00.237012,2023-09-27 05:16:02.408712,2171.700,2023-09-27 05:16:00.270,2023-09-27 05:16:02.218,1948.0
8,1636367,2023-09-27 05:16:00.237947,2023-09-27 05:16:01.808414,1570.467,2023-09-27 05:16:00.271,2023-09-27 05:16:01.784,1513.0
9,1589031,2023-09-27 05:16:00.239054,2023-09-27 05:16:01.855417,1616.363,2023-09-27 05:16:00.332,2023-09-27 05:16:01.826,1494.0